import { Poppins } from "next/font/google";
import "./globals.css";
import Footer from "@/component/footer/Footer";
import Navbar from "@/component/navbar/Navbar";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'], 
  display: 'swap',
});


export const metadata = {
  title: "MathWeb Latex",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className}>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
